# rds mariadb
spring:
  datasource:
  url: jdbc:mariadb://localhost:3306/fithub
  username: root
  password:
  driver-class-name: org.mariadb.jdbc.Driver

  messages:
    encoding=UTF-8:

  jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      format_sql: true

springboot:
  jwt:
    secret:

# aws
cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    s3:
      bucket: fithub-bucket
    credentials:
      access-key:
      secret-key:

